apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: employee-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
      - name: employee-service
        image: 118463809662.dkr.ecr.us-east-1.amazonaws.com/employee-repo
        ports:
        - containerPort: 80
